return PlaceObj('ModDef', {
	'title', "Tourist Specialization",
	'description', "Sets either Tourist specialization or No specialization for colonists who have Tourist trait. That makes filters work better.\nCustom icons for tourists will apply, so it's easier to spot them.\nBoth options, Specialization and Custom Icons, are configurable.\n\nIf you have any issues with the mod please contact me:\nakushnir2009@gmail.com\nhttps://github.com/a-kushnir/surviving-mars-mods",
	'image', "Preview.jpg",
	'last_changes', "Initial version",
	'id', "oF3o4Fg",
	'pops_desktop_uuid', "481b6877-321a-472e-ba18-ee8b5a48bb57",
	'pops_any_uuid', "ee8fb3c6-54c5-4023-9648-1337b6b027bc",
	'author', "Andrew Kushnir",
	'version_major', 1,
	'version', 13,
	'lua_revision', 1009413,
	'saved_with_revision', 1011166,
	'code', {
		"Code/Script.lua",
	},
	'has_options', true,
	'saved', 1655117561,
	'TagTraits', true,
})